# Generated by Django 3.0.6 on 2021-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
            ],
        ),
    ]
